name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          api-token: ${{ secrets.FLY_API_TOKEN }}

      - name: Build and Push Image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ../../deploy/
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.APP_NAME }}
          build-args: |
            FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }}

      - name: Deploy
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          api-token: ${{ secrets.FLY_API_TOKEN }}
          command: deploy
          app: ${{ env.APP_NAME }}
